### PR TITLE
fix(qbft): defer RoundTimer arming until callback is registered

### LINKED ISSUE #2753: fix(qbft): RoundTimer first-round timeout silently dropped due to late callback registration
## Problem

The `RoundTimer` is constructed with a nil callback (`done=nil`), armed for round 1 during `Instance.Start()`, and only receives its timeout callback when the runner calls `OnTimeout()` afterward. If the first-round timeout fires in that window, the callback is nil and the timeout is silently dropped.

### Call sequence

1. `roundtimer.New(ctx, ..., nil)` — timer created with nil callback (`operator/validator/controller.go:1027`, `:1088`)
2. `Controller.StartNewInstance()` → `Instance.Start()` — arms round 1 (`protocol/v2/qbft/instance/instance.go:110`)
3. Runner registers callback (`protocol/v2/ssv/runner/timer.go:20`)

For late-start duties where `RoundTimeout()` returns near-zero, the timer fires between steps 2 and 3.

### Impact

The instance misses its first round timeout, delaying the round bump when the proposer is offline. Recovery depends on receiving round-change messages from peers who did timeout.

## Possible approaches

**A. Pending-timeout replay inside RoundTimer** — If `done == nil` when the timer fires, store the pending round. When `OnTimeout()` is later called, replay if the context is still active and the round still matches. Contained to `roundtimer/timer.go` and tests.

**B. Restructure startup sequence** — Pass the callback through `StartNewInstance()` → `Start()`, or add an atomic "register callback + arm" API on `RoundTimer`. Cleaner long-term but touches controller, instance, runner, and spectests.

### PR DESCRIPTION
**Pull request by olegshmuelov**
## Summary

- Defer `RoundTimer` arming when the timeout callback is missing or stale from a previous duty, preventing silently dropped first-round timeouts on late-start duties
- Add height-aware `OnTimeout(height, done)` so `TimeoutForRound` can distinguish the current duty's callback from a stale one — deferred requests are replayed under the lock via `armLocked` once the correct callback is registered
- Stop and nil stale timers in the deferred path to suppress in-flight callbacks from previous duties

Closes #2753

## Finding

#2753 — RoundTimer first-round timeout silently dropped due to late callback registration

## Test

- 20 new deferred-arming tests across all 4 roles: first-duty nil callback, stale callback on duty N+1, stale timer stopped, deferred replaced by new round, context canceled before OnTimeout
- 28 existing tests pass unchanged
- `golangci-lint`: 0 issues

### CODE REVIEW

**Review by momosh-ssv — COMMENTED** [review]
The fix seems sound — two suggestions below.

File: protocol/v2/qbft/roundtimer/timer.go [hunk 1]
```diff
@@ -39,14 +39,27 @@ type TimeoutOptions struct {
...
 type RoundTimer struct {
 	mtx *sync.RWMutex
 	ctx context.Context
 	// timer is the underlying time.Timer
 	timer *time.Timer
-	// result holds the result of the timer
+	// done is the timeout callback for the current duty
 	done OnRoundTimeoutF
+	// doneHeight is the height for which done was registered
+	doneHeight specqbft.Height
```
Comment (momosh-ssv) [inline protocol/v2/qbft/roundtimer/timer.go]: Should we consider removing the `done` parameter from `New` now that `OnTimeout(height, done)` is the canonical registration path?

`New` sets `done` but leaves `doneHeight` at zero. This works because production callers pass `nil` and tests happen to use `FirstHeight == 0`, but if anyone passes a non-nil `done` for a non-zero height, `TimeoutForRound` will enter the deferred path, nil out the provided callback, and nobody calls `OnTimeout` to replay it — silently losing the timeout.

File: protocol/v2/qbft/roundtimer/timer.go [hunk 2]
```diff
@@ -148,35 +195,31 @@ func (t *RoundTimer) Round() specqbft.Round {
...
-	// Optimistic early-exit: a narrow window exists between this check and
-	// timer creation where ctx could be canceled; the callback re-checks
-	// ctx.Err() to handle that case.
 	if t.ctx.Err() != nil {
 		return
 	}
 
-	timeout := t.RoundTimeout(height, round)
-
 	t.mtx.Lock()
```
Comment (momosh-ssv) [inline protocol/v2/qbft/roundtimer/timer.go:208]: Worth considering `defer t.mtx.Unlock()` here for consistency with `OnTimeout`. Two manual unlock paths (lines 219, 224) work correctly today but reduce resilience to future edits — an added early return could forget the unlock.

File: protocol/v2/qbft/roundtimer/timer.go [hunk 3]
```diff
@@ -134,12 +146,48 @@ func (t *RoundTimer) RoundTimeout(height specqbft.Height, round specqbft.Round)
...
 
 	t.done = done
+	t.doneHeight = height
+	d := t.deferred
+	t.deferred = nil
+
+	// Replay the deferred arm now that the correct callback is registered.
+	// Done under the lock to linearize against concurrent TimeoutForRound
+	// calls from message processing (proposal, round-change, timeout bump).
+	if d != nil && d.height == height && t.ctx.Err() == nil {
```
Comment (iurii-ssv) [inline protocol/v2/qbft/roundtimer/timer.go]: Probably cleaner to have this `t.ctx.Err() == nil` be the very 1st thing `OnTimeout` func check

File: protocol/v2/qbft/roundtimer/timer.go (hunk 1 above)
Comment (iurii-ssv) [inline protocol/v2/qbft/roundtimer/timer.go]: Nit: could `done`->`callback` and `doneHeight`->`callbackHeight` for clarity

File: protocol/v2/qbft/roundtimer/timer.go [hunk 4]
```diff
@@ -148,40 +196,34 @@ func (t *RoundTimer) Round() specqbft.Round {
...
 
-	timeout := t.RoundTimeout(height, round)
-
 	t.mtx.Lock()
+	defer t.mtx.Unlock()
+
 	// round is read lock-free via Round(), so accesses stay atomic.
 	// The store happens while t.mtx is held only to keep round updates
 	// linearized with timer/done/deferred state changes.
 	atomic.StoreUint64(&t.round, uint64(round))
```
Comment (iurii-ssv) [inline protocol/v2/qbft/roundtimer/timer.go]: We are updating `t.round` unconditionally here (regardless of what `height` it belongs to), this seems dangerous to me, can't we overwrite the `t.round` that was stored there for the current height with a round-value from some previous height (due to a delayed `TimeoutForRound` that was targeting the duty for the previous slot) ?

**Review by iurii-ssv — COMMENTED** [review]
An improvement over what we had for sure, 

**Discussion**: don't like that `RoundTimer` is duty-height dependent though (maybe we could spawn 1 per duty instead ?) ... Would be nice to make it more abstract (the fact that it works with the "current duty" is very error-prone since "current" can mean slot N or slot N+1 at the slot boundary). Makes me feel like `RoundTimer` needs to enforce monotonic `doneHeight` increases somewhere at the very least (unless it's already done implicitly somehow).

File: protocol/v2/qbft/roundtimer/timer.go (hunk 4 above)
Comment (olegshmuelov) [reply protocol/v2/qbft/roundtimer/timer.go]: Good catch, real correctness issue. Fixed:
- `t.round` only set inside `armLocked`, not unconditionally in `TimeoutForRound`
- Monotonic height guards in both `OnTimeout` and `TimeoutForRound`
- `callbackHeight` advances in the deferred path, closing the window between `TimeoutForRound(H+1)` and `OnTimeout(H+1)`
- New test `testStaleDuringDeferredWindow` covers the exact interleaving

**Comment by olegshmuelov** [comment]
> An improvement over what we had for sure,
> 
> **Discussion**: don't like that `RoundTimer` is duty-height dependent though (maybe we could spawn 1 per duty instead ?) ... Would be nice to make it more abstract (the fact that it works with the "current duty" is very error-prone since "current" can mean slot N or slot N+1 at the slot boundary). Makes me feel like `RoundTimer` needs to enforce monotonic `doneHeight` increases somewhere at the very least (unless it's already done implicitly somehow).

Agree that a per-duty timer would eliminate the height-tracking complexity entirely. It's the right direction, I'd like to take that on as a follow-up once the goroutine-leak base lands on stage.

For this PR: both `OnTimeout` and `TimeoutForRound` now enforce monotonic height increases, and `callbackHeight` advances in the deferred path too, so the stale-call surface is fully closed.

**Review by iurii-ssv — DISMISSED** [review]
Looks correct to me, I would strongly recommend we refactor it further to at least implement "per duty timer" to keep the complexity of this code manageable (as a follow-up Issue/PR).

**Review by momosh-ssv — DISMISSED** [review]
see no issues here, nice one!

**Review by ljuba-ssv — DISMISSED** [review]

File: protocol/v2/qbft/roundtimer/timer.go [hunk 5]
```diff
@@ -133,47 +145,87 @@ func (t *RoundTimer) RoundTimeout(height specqbft.Height, round specqbft.Round)
...
+	// calls from message processing (proposal, round-change, timeout bump).
+	if d != nil && d.height == height {
+		t.armLocked(d.height, d.round)
+	}
+}
+
+// TimeoutForRound stops any running timer and schedules a callback for the given round.
+// If the callback is not yet registered for this duty's height (nil or stale from a
+// previous duty), the request is deferred until OnTimeout registers the correct callback.
+func (t *RoundTimer) TimeoutForRound(height specqbft.Height, round specqbft.Round) {
```
Comment (iurii-ssv) [inline protocol/v2/qbft/roundtimer/timer.go]: Seems the new comment (1st line of it) overrides previous description that's a bit more comprehensive:
```
// TimeoutForRound stops any running timer, waits for any in-flight callback to
// finish, and schedules a new callback for the given round.
```

**Review by iurii-ssv — DISMISSED** [review]
Just a minor thing

**Review by momosh-ssv — DISMISSED** [review]

**Review by ljuba-ssv — DISMISSED** [review]

**Review by iurii-ssv — APPROVED** [review]

**Review by ljuba-ssv — APPROVED** [review]
